version: '3.8'

services:
  ner-service:
    build:
      context: ./backend/NER-Service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  backend:
    build:
      context: ./backend/node
    ports:
      - "5000:5000"
    environment:
      - NER_API_URL=http://ner-service:8000/ner
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    depends_on:
      - ner-service
